"""
Configuration file for pairs trading strategy
"""
import os

# Data settings
DATA_START_DATE = '2023-01-01'
DATA_END_DATE = '2025-11-26'
MIN_DATA_POINTS = 200

ASX200_TICKERS = [
    'CBA.AX',
    'BHP.AX',
    'NAB.AX',
    'WBC.AX',
    'WES.AX',
    'CSL.AX',
    'MQG.AX',
    'GMG.AX',
    'FMG.AX',
    'RIO.AX',
    'TCL.AX',
    'WDS.AX',
    'ALL.AX',
    'NST.AX',
    'BXB.AX',
    'SIG.AX',
    'QBE.AX',
    'WOW.AX',
    'COL.AX',
    'PME.AX',
    'REA.AX',
    'WTC.AX',
    'XRO.AX',
    'RMD.AX',
    'EVN.AX',
    'STO.AX',
    'SUN.AX',
    'CPU.AX',
    'ORG.AX',
    'SCG.AX',
    'FPH.AX',
    'IAG.AX',
    'COH.AX',
    'QAN.AX',
    'SGP.AX',
    'CAR.AX',
    'NEM.AX',
    'SOL.AX',
    'JHX.AX',
    'JBH.AX',
    'MPL.AX',
    'S32.AX',
    'TLC.AX',
    'APA.AX',
    'AIA.AX',
    'VCX.AX',
    'ALQ.AX',
    'ASX.AX',
    'CHC.AX',
    'IFT.AX',
    'NXT.AX',
    'SHL.AX',
    'GPT.AX',
    'ORI.AX',
    'SEK.AX',
    'BSL.AX',
    'TPG.AX',
    '360.AX',
    'MGR.AX',
    'AMC.AX',
    'PLS.AX',
    'HUB.AX',
    'MCY.AX',
    'MIN.AX',
    'RMS.AX',
    'QUB.AX',
    'BEN.AX',
    'NWL.AX',
    'WOR.AX',
    'ALD.AX',
    'RHC.AX',
    'REH.AX',
    'SFR.AX',
    'GMD.AX',
    'YAL.AX',
    'PRU.AX',
    'SDF.AX',
    'MEZ.AX',
    'CWY.AX',
    'ZIP.AX',
    'AGL.AX',
    'CGF.AX',
    'CDA.AX',
    'AZJ.AX',
    'DRO.AX',
    'TWE.AX',
    'WHC.AX',
    'EBO.AX',
    'WGX.AX',
    'DOW.AX',
    'TLX.AX',
    'GQG.AX',
    'ANN.AX',
    'BOQ.AX',
    'XYZ.AX',
    'VNT.AX',
    'PNI.AX',
    'AMP.AX',
    'LOV.AX',
    'MTS.AX',
    'IGO.AX',
    '79.AX',
    'SPK.AX',
    'AUB.AX',
    'GOR.AX',
    'PDN.AX',
    'CEN.AX',
    'LLC.AX',
    'NHF.AX',
    'BFL.AX',
    'CNU.AX',
    'ASB.AX',
    'WAF.AX',
    'EMR.AX',
    'FBU.AX',
    'NHC.AX',
    'NIC.AX',
    'ARB.AX',
    'ILU.AX',
    'RWC.AX',
    'IFL.AX',
    'VEA.AX',
    'AAI.AX',
    'LTR.AX',
    'VGN.AX',
    'CSC.AX',
    'TPW.AX',
    'BPT.AX',
    'BWP.AX',
    'IPX.AX',
    'NEU.AX',
    'PRN.AX',
    'RGN.AX',
    'CIA.AX',
    'MP1.AX',
    'ORA.AX',
    'PNR.AX',
    'RYM.AX',
    'FLT.AX',
    'CTD.AX',
    'OBM.AX',
    'TAH.AX',
    'GNE.AX',
    'INA.AX',
    'MND.AX',
    'PPT.AX',
    'RSG.AX',
    'DBI.AX',
    'FRW.AX',
    'CAT.AX',
    'DTR.AX',
    'EVT.AX',
    'NWH.AX',
    'SDR.AX',
    'ZIM.AX',
    'CYL.AX',
    'DYL.AX',
    'GNC.AX',
    'JDO.AX',
    'NWS.AX',
    'REG.AX',
    'COF.AX',
    'CU6.AX',
    'NCK.AX',
    'SLX.AX',
    'WLE.AX',
    'ASK.AX',
    'BGL.AX',
    'DDR.AX',
    'EOS.AX',
    'IEL.AX',
    'ANZ.AX',
    'TLS.AX',
    'SGH.AX',
    'LYC.AX',
    'TNE.AX',
    'HVN.AX',
    'ALX.AX',
    'A2M.AX',
    'EDV.AX',
    'DNL.AX',
    'CMM.AX',
    'GGP.AX',
    'VAU.AX',
    'RRL.AX',
    'BRG.AX',
    'TUA.AX',
    'SUL.AX',
    'MSB.AX',
    'PMV.AX',
    'GDG.AX',
    'PXA.AX',
    'GYG.AX',
    'SGM.AX',
    'SNZ.AX',
    'NEC.AX',
    'OCL.AX',
    'SMR.AX',
    'IMD.AX',
    'APE.AX',
]

# Cointegration settings
MIN_CORRELATION = 0.7
COINTEGRATION_PVALUE_THRESHOLD = 0.05
ZSCORE_WINDOW = 20

# Trading settings
INITIAL_CASH = 100000
TRANSACTION_COST = 0.001  # 0.1%
POSITION_SIZE_PCT = 0.01  # 1% of capital per pair

# Signal thresholds
ZSCORE_ENTRY_LONG = -2.0
ZSCORE_ENTRY_SHORT = 2.0
ZSCORE_EXIT = 0.5
ZSCORE_STOP_LOSS = 3.0

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DATA_DIR = os.path.join(DATA_DIR, 'raw')
PROCESSED_DATA_DIR = os.path.join(DATA_DIR, 'processed')
REPORTS_DIR = os.path.join(BASE_DIR, 'reports')